#!/usr/bin/env python3

import sys
import subprocess
import re

def main():
    lib_name = sys.argv[1]
    object_file = sys.argv[2]

    result = subprocess.run(['nm', object_file], capture_output=True, text=True)
    nm_output = result.stdout

    finfo_pattern = re.compile(r'pg_finfo_(\w+)')
    functions = []

    for line in nm_output.splitlines():
        match = finfo_pattern.search(line)
        if match:
            func_name = match.group(1)
            functions.append(func_name)

    assert len(functions) > 0, "No pg_finfo symbols found"

    print(f"/*")
    print(f" * {lib_name}_static.c - Static wrapper for {lib_name} extension")
    print(f" *")
    print(f" * Auto-generated by gen_static_extension.py")
    print(f" */")
    print()
    print('#include "postgres.h"')
    print('#include "fmgr.h"')
    print('#include "extensions.h"')
    print()

    for func in functions:
        print(f"extern Datum {func}(PG_FUNCTION_ARGS);")
    print()

    for func in functions:
        print(f"extern const Pg_finfo_record *pg_finfo_{func}(void);")
    print()

    print(f"extern void {lib_name}_PG_init(void);")
    print()

    print(f"const StaticExtensionFunc {lib_name}_static_functions[] = {{")
    for func in functions:
        print(f'\t{{"{func}", {func}}},')
    print("\t{NULL, NULL}")
    print("};")
    print()

    print(f"const StaticExtensionFInfo {lib_name}_static_finfo[] = {{")
    for func in functions:
        print(f'\t{{"pg_finfo_{func}", pg_finfo_{func}}},')
    print("\t{NULL, NULL}")
    print("};")
    print()

    print("void")
    print(f"register_{lib_name}(void)")
    print("{")
    print("\tregister_static_extension(")
    print(f'\t\t"{lib_name}",')
    print(f"\t\t{lib_name}_PG_init,")
    print(f"\t\t{lib_name}_static_functions,")
    print(f"\t\t{lib_name}_static_finfo")
    print("\t);")
    print("}")

if __name__ == "__main__":
    main()
