#!/usr/bin/env python3

import sys
import subprocess
import re
import os

def xxd(fname, varname) -> str:
    p = subprocess.Popen(
        ['xxd', '-include', '-name', varname],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
    )
    stdout, _ = p.communicate(open(fname, 'rb').read())
    out = stdout.decode('utf-8').replace("unsigned", "const unsigned")
    return out

def generate_data_h(lib_name, control_file, script_file, output_file):
    """Generate data.h with embedded file data using xxd"""
    with open(output_file, 'w') as f:
        f.write(f"/*\n")
        f.write(f" * data.h - Embedded extension files for {lib_name}\n")
        f.write(f" * Auto-generated by gen_static_extension.py\n")
        f.write(f" */\n\n")

        if control_file and os.path.exists(control_file):
            out = xxd(control_file, f'{lib_name}_control')
            f.write(out)
            f.write('\n')

        if script_file and os.path.exists(script_file):
            out = xxd(script_file, f'{lib_name}_script')
            f.write(out)
            f.write('\n')

def main():
    lib_name = sys.argv[1]
    object_file = sys.argv[2]
    control_file = sys.argv[3] if len(sys.argv) > 3 else None
    script_file = sys.argv[4] if len(sys.argv) > 4 else None
    # TODO: parse from control_file
    version = sys.argv[5] if len(sys.argv) > 5 else None

    result = subprocess.run(['nm', object_file], capture_output=True, text=True)
    nm_output = result.stdout

    finfo_pattern = re.compile(r'pg_finfo_(\w+)')
    functions = []

    for line in nm_output.splitlines():
        match = finfo_pattern.search(line)
        if match:
            func_name = match.group(1)
            functions.append(func_name)

    assert len(functions) > 0, "No pg_finfo symbols found"

    print(f"/*")
    print(f" * {lib_name}_static.c - Static wrapper for {lib_name} extension")
    print(f" *")
    print(f" * Auto-generated by gen_static_extension.py")
    print(f" */")
    print()
    print('#include "postgres.h"')
    print('#include "fmgr.h"')
    print('#include "extensions.h"')
    print()

    for func in functions:
        print(f"extern Datum {func}(PG_FUNCTION_ARGS);")
    print()

    for func in functions:
        print(f"extern const Pg_finfo_record *pg_finfo_{func}(void);")
    print()

    print(f"extern void {lib_name}_PG_init(void);")
    print()

    print(f"const StaticExtensionFunc {lib_name}_static_functions[] = {{")
    for func in functions:
        print(f'\t{{"{func}", {func}}},')
    print("\t{NULL, NULL}")
    print("};")
    print()

    print(f"const StaticExtensionFInfo {lib_name}_static_finfo[] = {{")
    for func in functions:
        print(f'\t{{"pg_finfo_{func}", pg_finfo_{func}}},')
    print("\t{NULL, NULL}")
    print("};")
    print()

    has_embedded_files = control_file or script_file

    if has_embedded_files:
        data_h_file = f"{lib_name}_data.h"
        generate_data_h(lib_name, control_file, script_file, data_h_file)
        print(f'#include "{data_h_file}"')
        print()

    print("void")
    print(f"register_{lib_name}(void)")
    print("{")

    if has_embedded_files:
        if control_file:
            print(f"\tstatic const EmbeddedFile control_file = {{")
            print(f'\t\t.filename = "/tmp/pg-embedded-install/share/postgresql/extension/{lib_name}.control",')
            print(f"\t\t.data = {lib_name}_control,")
            print(f"\t\t.len = {lib_name}_control_len")
            print("\t};")

        if script_file:
            print(f"\tstatic const EmbeddedFile script_file = {{")
            print(f'\t\t.filename = "/tmp/pg-embedded-install/share/postgresql/extension/{lib_name}--{version}.sql",')
            print(f"\t\t.data = {lib_name}_script,")
            print(f"\t\t.len = {lib_name}_script_len")
            print("\t};")
        print()

    control_ptr = "&control_file" if control_file else "NULL"
    script_ptr = "&script_file" if script_file else "NULL"

    print("\tregister_static_extension(")
    print(f'\t\t"{lib_name}",')
    print(f"\t\t{lib_name}_PG_init,")
    print(f"\t\t{lib_name}_static_functions,")
    print(f"\t\t{lib_name}_static_finfo,")
    print(f"\t\t{control_ptr},")
    print(f"\t\t{script_ptr}")
    print("\t);")
    print("}")

if __name__ == "__main__":
    main()
