/*
 * plpgsql_static.c - Static wrapper for plpgsql extension
 *
 * Auto-generated by gen_static_extension.py
 */

#include "postgres.h"
#include "fmgr.h"
#include "extensions.h"

extern Datum plpgsql_call_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_inline_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_validator(PG_FUNCTION_ARGS);

extern const Pg_finfo_record *pg_finfo_plpgsql_call_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_inline_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_validator(void);

extern void plpgsql_PG_init(void);

const StaticExtensionFunc plpgsql_static_functions[] = {
	{"plpgsql_call_handler", plpgsql_call_handler},
	{"plpgsql_inline_handler", plpgsql_inline_handler},
	{"plpgsql_validator", plpgsql_validator},
	{NULL, NULL}
};

const StaticExtensionFInfo plpgsql_static_finfo[] = {
	{"pg_finfo_plpgsql_call_handler", pg_finfo_plpgsql_call_handler},
	{"pg_finfo_plpgsql_inline_handler", pg_finfo_plpgsql_inline_handler},
	{"pg_finfo_plpgsql_validator", pg_finfo_plpgsql_validator},
	{NULL, NULL}
};

#include "plpgsql_data.h"

void
register_plpgsql(void)
{
	static const EmbeddedFile control_file = {
		.filename = "share/extension/plpgsql.control",
		.data = plpgsql_control,
		.len = plpgsql_control_len
	};
	static const EmbeddedFile script_file = {
		.filename = "share/extension/plpgsql.sql",
		.data = plpgsql_script,
		.len = plpgsql_script_len
	};

	register_static_extension(
		"plpgsql",
		plpgsql_PG_init,
		plpgsql_static_functions,
		plpgsql_static_finfo,
		&control_file,
		&script_file
	);
}
