/*
 * plpgsql_static.c - Static wrapper for PL/pgSQL extension
 *
 * This wrapper allows PL/pgSQL to be statically linked instead of
 * dynamically loaded. It references the handler functions from the
 * compiled plpgsql object files.
 */

#include "postgres.h"
#include "fmgr.h"

/*
 * External declarations for functions implemented in pl_handler.o
 * These are already compiled in vendor/pg18/src/pl/plpgsql/src/*.o
 */
extern Datum plpgsql_call_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_inline_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_validator(PG_FUNCTION_ARGS);

/*
 * External declarations for pg_finfo functions
 * These are automatically generated by PG_FUNCTION_INFO_V1 macro
 * in pl_handler.c
 */
extern const Pg_finfo_record *pg_finfo_plpgsql_call_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_inline_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_validator(void);

/*
 * External declaration for _PG_init
 * The initialization function from pl_handler.c
 * (renamed to avoid conflicts with other extensions)
 */
extern void plpgsql_PG_init(void);

/*
 * External declaration for Pg_magic_func
 * Defined by PG_MODULE_MAGIC in pl_handler.c
 * (renamed to avoid conflicts with other extensions)
 */
extern const Pg_magic_struct *plpgsql_Pg_magic_func(void);

/*
 * Function metadata table for static registration
 */
const StaticExtensionFunc plpgsql_static_functions[] = {
	{"plpgsql_call_handler", plpgsql_call_handler, pg_finfo_plpgsql_call_handler},
	{"plpgsql_inline_handler", plpgsql_inline_handler, pg_finfo_plpgsql_inline_handler},
	{"plpgsql_validator", plpgsql_validator, pg_finfo_plpgsql_validator},
	{NULL, NULL, NULL}
};

void
register_pl_pgsql(void)
{
	register_static_extension(
		"plpgsql",
		plpgsql_Pg_magic_func(),
		plpgsql_PG_init,
		plpgsql_static_functions
	);
}
