/*
 * example_static.c - Static wrapper for example extension
 *
 * Auto-generated by gen_static_extension.py
 */

#include "postgres.h"
#include "fmgr.h"
#include "extensions.h"

extern Datum add_one(PG_FUNCTION_ARGS);
extern Datum hello_world(PG_FUNCTION_ARGS);

extern const Pg_finfo_record *pg_finfo_add_one(void);
extern const Pg_finfo_record *pg_finfo_hello_world(void);

extern void example_PG_init(void);

const StaticExtensionFunc example_static_functions[] = {
	{"add_one", add_one},
	{"hello_world", hello_world},
	{NULL, NULL}
};

const StaticExtensionFInfo example_static_finfo[] = {
	{"pg_finfo_add_one", pg_finfo_add_one},
	{"pg_finfo_hello_world", pg_finfo_hello_world},
	{NULL, NULL}
};

#include "example_data.h"

void
register_example(void)
{
	static const EmbeddedFile control_file = {
		.filename = "/tmp/pg-embedded-install/share/postgresql/extension/example.control",
		.data = example_control,
		.len = example_control_len
	};
	static const EmbeddedFile script_file = {
		.filename = "/tmp/pg-embedded-install/share/postgresql/extension/example--1.0.sql",
		.data = example_script,
		.len = example_script_len
	};

	register_static_extension(
		"example",
		example_PG_init,
		example_static_functions,
		example_static_finfo,
		&control_file,
		&script_file
	);
}
