/*
 * pgvector_static.c - Static wrapper for pgvector extension
 *
 * Auto-generated by gen_static_extension.py
 */

#include "postgres.h"
#include "fmgr.h"
#include "extensions.h"

extern Datum hamming_distance(PG_FUNCTION_ARGS);
extern Datum jaccard_distance(PG_FUNCTION_ARGS);
extern Datum array_to_halfvec(PG_FUNCTION_ARGS);
extern Datum halfvec(PG_FUNCTION_ARGS);
extern Datum halfvec_accum(PG_FUNCTION_ARGS);
extern Datum halfvec_add(PG_FUNCTION_ARGS);
extern Datum halfvec_avg(PG_FUNCTION_ARGS);
extern Datum halfvec_binary_quantize(PG_FUNCTION_ARGS);
extern Datum halfvec_cmp(PG_FUNCTION_ARGS);
extern Datum halfvec_concat(PG_FUNCTION_ARGS);
extern Datum halfvec_cosine_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_eq(PG_FUNCTION_ARGS);
extern Datum halfvec_ge(PG_FUNCTION_ARGS);
extern Datum halfvec_gt(PG_FUNCTION_ARGS);
extern Datum halfvec_in(PG_FUNCTION_ARGS);
extern Datum halfvec_inner_product(PG_FUNCTION_ARGS);
extern Datum halfvec_l1_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_l2_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_l2_norm(PG_FUNCTION_ARGS);
extern Datum halfvec_l2_normalize(PG_FUNCTION_ARGS);
extern Datum halfvec_l2_squared_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_le(PG_FUNCTION_ARGS);
extern Datum halfvec_lt(PG_FUNCTION_ARGS);
extern Datum halfvec_mul(PG_FUNCTION_ARGS);
extern Datum halfvec_ne(PG_FUNCTION_ARGS);
extern Datum halfvec_negative_inner_product(PG_FUNCTION_ARGS);
extern Datum halfvec_out(PG_FUNCTION_ARGS);
extern Datum halfvec_recv(PG_FUNCTION_ARGS);
extern Datum halfvec_send(PG_FUNCTION_ARGS);
extern Datum halfvec_spherical_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_sub(PG_FUNCTION_ARGS);
extern Datum halfvec_subvector(PG_FUNCTION_ARGS);
extern Datum halfvec_to_float4(PG_FUNCTION_ARGS);
extern Datum halfvec_typmod_in(PG_FUNCTION_ARGS);
extern Datum halfvec_vector_dims(PG_FUNCTION_ARGS);
extern Datum sparsevec_to_halfvec(PG_FUNCTION_ARGS);
extern Datum vector_to_halfvec(PG_FUNCTION_ARGS);
extern Datum hnswhandler(PG_FUNCTION_ARGS);
extern Datum hnsw_bit_support(PG_FUNCTION_ARGS);
extern Datum hnsw_halfvec_support(PG_FUNCTION_ARGS);
extern Datum hnsw_sparsevec_support(PG_FUNCTION_ARGS);
extern Datum ivfflathandler(PG_FUNCTION_ARGS);
extern Datum ivfflat_bit_support(PG_FUNCTION_ARGS);
extern Datum ivfflat_halfvec_support(PG_FUNCTION_ARGS);
extern Datum array_to_sparsevec(PG_FUNCTION_ARGS);
extern Datum halfvec_to_sparsevec(PG_FUNCTION_ARGS);
extern Datum sparsevec(PG_FUNCTION_ARGS);
extern Datum sparsevec_cmp(PG_FUNCTION_ARGS);
extern Datum sparsevec_cosine_distance(PG_FUNCTION_ARGS);
extern Datum sparsevec_eq(PG_FUNCTION_ARGS);
extern Datum sparsevec_ge(PG_FUNCTION_ARGS);
extern Datum sparsevec_gt(PG_FUNCTION_ARGS);
extern Datum sparsevec_in(PG_FUNCTION_ARGS);
extern Datum sparsevec_inner_product(PG_FUNCTION_ARGS);
extern Datum sparsevec_l1_distance(PG_FUNCTION_ARGS);
extern Datum sparsevec_l2_distance(PG_FUNCTION_ARGS);
extern Datum sparsevec_l2_norm(PG_FUNCTION_ARGS);
extern Datum sparsevec_l2_normalize(PG_FUNCTION_ARGS);
extern Datum sparsevec_l2_squared_distance(PG_FUNCTION_ARGS);
extern Datum sparsevec_le(PG_FUNCTION_ARGS);
extern Datum sparsevec_lt(PG_FUNCTION_ARGS);
extern Datum sparsevec_ne(PG_FUNCTION_ARGS);
extern Datum sparsevec_negative_inner_product(PG_FUNCTION_ARGS);
extern Datum sparsevec_out(PG_FUNCTION_ARGS);
extern Datum sparsevec_recv(PG_FUNCTION_ARGS);
extern Datum sparsevec_send(PG_FUNCTION_ARGS);
extern Datum sparsevec_typmod_in(PG_FUNCTION_ARGS);
extern Datum vector_to_sparsevec(PG_FUNCTION_ARGS);
extern Datum array_to_vector(PG_FUNCTION_ARGS);
extern Datum binary_quantize(PG_FUNCTION_ARGS);
extern Datum cosine_distance(PG_FUNCTION_ARGS);
extern Datum halfvec_to_vector(PG_FUNCTION_ARGS);
extern Datum inner_product(PG_FUNCTION_ARGS);
extern Datum l1_distance(PG_FUNCTION_ARGS);
extern Datum l2_distance(PG_FUNCTION_ARGS);
extern Datum l2_normalize(PG_FUNCTION_ARGS);
extern Datum sparsevec_to_vector(PG_FUNCTION_ARGS);
extern Datum subvector(PG_FUNCTION_ARGS);
extern Datum vector(PG_FUNCTION_ARGS);
extern Datum vector_accum(PG_FUNCTION_ARGS);
extern Datum vector_add(PG_FUNCTION_ARGS);
extern Datum vector_avg(PG_FUNCTION_ARGS);
extern Datum vector_cmp(PG_FUNCTION_ARGS);
extern Datum vector_combine(PG_FUNCTION_ARGS);
extern Datum vector_concat(PG_FUNCTION_ARGS);
extern Datum vector_dims(PG_FUNCTION_ARGS);
extern Datum vector_eq(PG_FUNCTION_ARGS);
extern Datum vector_ge(PG_FUNCTION_ARGS);
extern Datum vector_gt(PG_FUNCTION_ARGS);
extern Datum vector_in(PG_FUNCTION_ARGS);
extern Datum vector_l2_squared_distance(PG_FUNCTION_ARGS);
extern Datum vector_le(PG_FUNCTION_ARGS);
extern Datum vector_lt(PG_FUNCTION_ARGS);
extern Datum vector_mul(PG_FUNCTION_ARGS);
extern Datum vector_ne(PG_FUNCTION_ARGS);
extern Datum vector_negative_inner_product(PG_FUNCTION_ARGS);
extern Datum vector_norm(PG_FUNCTION_ARGS);
extern Datum vector_out(PG_FUNCTION_ARGS);
extern Datum vector_recv(PG_FUNCTION_ARGS);
extern Datum vector_send(PG_FUNCTION_ARGS);
extern Datum vector_spherical_distance(PG_FUNCTION_ARGS);
extern Datum vector_sub(PG_FUNCTION_ARGS);
extern Datum vector_to_float4(PG_FUNCTION_ARGS);
extern Datum vector_typmod_in(PG_FUNCTION_ARGS);

extern const Pg_finfo_record *pg_finfo_hamming_distance(void);
extern const Pg_finfo_record *pg_finfo_jaccard_distance(void);
extern const Pg_finfo_record *pg_finfo_array_to_halfvec(void);
extern const Pg_finfo_record *pg_finfo_halfvec(void);
extern const Pg_finfo_record *pg_finfo_halfvec_accum(void);
extern const Pg_finfo_record *pg_finfo_halfvec_add(void);
extern const Pg_finfo_record *pg_finfo_halfvec_avg(void);
extern const Pg_finfo_record *pg_finfo_halfvec_binary_quantize(void);
extern const Pg_finfo_record *pg_finfo_halfvec_cmp(void);
extern const Pg_finfo_record *pg_finfo_halfvec_concat(void);
extern const Pg_finfo_record *pg_finfo_halfvec_cosine_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_eq(void);
extern const Pg_finfo_record *pg_finfo_halfvec_ge(void);
extern const Pg_finfo_record *pg_finfo_halfvec_gt(void);
extern const Pg_finfo_record *pg_finfo_halfvec_in(void);
extern const Pg_finfo_record *pg_finfo_halfvec_inner_product(void);
extern const Pg_finfo_record *pg_finfo_halfvec_l1_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_l2_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_l2_norm(void);
extern const Pg_finfo_record *pg_finfo_halfvec_l2_normalize(void);
extern const Pg_finfo_record *pg_finfo_halfvec_l2_squared_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_le(void);
extern const Pg_finfo_record *pg_finfo_halfvec_lt(void);
extern const Pg_finfo_record *pg_finfo_halfvec_mul(void);
extern const Pg_finfo_record *pg_finfo_halfvec_ne(void);
extern const Pg_finfo_record *pg_finfo_halfvec_negative_inner_product(void);
extern const Pg_finfo_record *pg_finfo_halfvec_out(void);
extern const Pg_finfo_record *pg_finfo_halfvec_recv(void);
extern const Pg_finfo_record *pg_finfo_halfvec_send(void);
extern const Pg_finfo_record *pg_finfo_halfvec_spherical_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_sub(void);
extern const Pg_finfo_record *pg_finfo_halfvec_subvector(void);
extern const Pg_finfo_record *pg_finfo_halfvec_to_float4(void);
extern const Pg_finfo_record *pg_finfo_halfvec_typmod_in(void);
extern const Pg_finfo_record *pg_finfo_halfvec_vector_dims(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_to_halfvec(void);
extern const Pg_finfo_record *pg_finfo_vector_to_halfvec(void);
extern const Pg_finfo_record *pg_finfo_hnswhandler(void);
extern const Pg_finfo_record *pg_finfo_hnsw_bit_support(void);
extern const Pg_finfo_record *pg_finfo_hnsw_halfvec_support(void);
extern const Pg_finfo_record *pg_finfo_hnsw_sparsevec_support(void);
extern const Pg_finfo_record *pg_finfo_ivfflathandler(void);
extern const Pg_finfo_record *pg_finfo_ivfflat_bit_support(void);
extern const Pg_finfo_record *pg_finfo_ivfflat_halfvec_support(void);
extern const Pg_finfo_record *pg_finfo_array_to_sparsevec(void);
extern const Pg_finfo_record *pg_finfo_halfvec_to_sparsevec(void);
extern const Pg_finfo_record *pg_finfo_sparsevec(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_cmp(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_cosine_distance(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_eq(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_ge(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_gt(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_in(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_inner_product(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_l1_distance(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_l2_distance(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_l2_norm(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_l2_normalize(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_l2_squared_distance(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_le(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_lt(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_ne(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_negative_inner_product(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_out(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_recv(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_send(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_typmod_in(void);
extern const Pg_finfo_record *pg_finfo_vector_to_sparsevec(void);
extern const Pg_finfo_record *pg_finfo_array_to_vector(void);
extern const Pg_finfo_record *pg_finfo_binary_quantize(void);
extern const Pg_finfo_record *pg_finfo_cosine_distance(void);
extern const Pg_finfo_record *pg_finfo_halfvec_to_vector(void);
extern const Pg_finfo_record *pg_finfo_inner_product(void);
extern const Pg_finfo_record *pg_finfo_l1_distance(void);
extern const Pg_finfo_record *pg_finfo_l2_distance(void);
extern const Pg_finfo_record *pg_finfo_l2_normalize(void);
extern const Pg_finfo_record *pg_finfo_sparsevec_to_vector(void);
extern const Pg_finfo_record *pg_finfo_subvector(void);
extern const Pg_finfo_record *pg_finfo_vector(void);
extern const Pg_finfo_record *pg_finfo_vector_accum(void);
extern const Pg_finfo_record *pg_finfo_vector_add(void);
extern const Pg_finfo_record *pg_finfo_vector_avg(void);
extern const Pg_finfo_record *pg_finfo_vector_cmp(void);
extern const Pg_finfo_record *pg_finfo_vector_combine(void);
extern const Pg_finfo_record *pg_finfo_vector_concat(void);
extern const Pg_finfo_record *pg_finfo_vector_dims(void);
extern const Pg_finfo_record *pg_finfo_vector_eq(void);
extern const Pg_finfo_record *pg_finfo_vector_ge(void);
extern const Pg_finfo_record *pg_finfo_vector_gt(void);
extern const Pg_finfo_record *pg_finfo_vector_in(void);
extern const Pg_finfo_record *pg_finfo_vector_l2_squared_distance(void);
extern const Pg_finfo_record *pg_finfo_vector_le(void);
extern const Pg_finfo_record *pg_finfo_vector_lt(void);
extern const Pg_finfo_record *pg_finfo_vector_mul(void);
extern const Pg_finfo_record *pg_finfo_vector_ne(void);
extern const Pg_finfo_record *pg_finfo_vector_negative_inner_product(void);
extern const Pg_finfo_record *pg_finfo_vector_norm(void);
extern const Pg_finfo_record *pg_finfo_vector_out(void);
extern const Pg_finfo_record *pg_finfo_vector_recv(void);
extern const Pg_finfo_record *pg_finfo_vector_send(void);
extern const Pg_finfo_record *pg_finfo_vector_spherical_distance(void);
extern const Pg_finfo_record *pg_finfo_vector_sub(void);
extern const Pg_finfo_record *pg_finfo_vector_to_float4(void);
extern const Pg_finfo_record *pg_finfo_vector_typmod_in(void);

extern void pgvector_PG_init(void);

const StaticExtensionFunc pgvector_static_functions[] = {
	{"hamming_distance", hamming_distance},
	{"jaccard_distance", jaccard_distance},
	{"array_to_halfvec", array_to_halfvec},
	{"halfvec", halfvec},
	{"halfvec_accum", halfvec_accum},
	{"halfvec_add", halfvec_add},
	{"halfvec_avg", halfvec_avg},
	{"halfvec_binary_quantize", halfvec_binary_quantize},
	{"halfvec_cmp", halfvec_cmp},
	{"halfvec_concat", halfvec_concat},
	{"halfvec_cosine_distance", halfvec_cosine_distance},
	{"halfvec_eq", halfvec_eq},
	{"halfvec_ge", halfvec_ge},
	{"halfvec_gt", halfvec_gt},
	{"halfvec_in", halfvec_in},
	{"halfvec_inner_product", halfvec_inner_product},
	{"halfvec_l1_distance", halfvec_l1_distance},
	{"halfvec_l2_distance", halfvec_l2_distance},
	{"halfvec_l2_norm", halfvec_l2_norm},
	{"halfvec_l2_normalize", halfvec_l2_normalize},
	{"halfvec_l2_squared_distance", halfvec_l2_squared_distance},
	{"halfvec_le", halfvec_le},
	{"halfvec_lt", halfvec_lt},
	{"halfvec_mul", halfvec_mul},
	{"halfvec_ne", halfvec_ne},
	{"halfvec_negative_inner_product", halfvec_negative_inner_product},
	{"halfvec_out", halfvec_out},
	{"halfvec_recv", halfvec_recv},
	{"halfvec_send", halfvec_send},
	{"halfvec_spherical_distance", halfvec_spherical_distance},
	{"halfvec_sub", halfvec_sub},
	{"halfvec_subvector", halfvec_subvector},
	{"halfvec_to_float4", halfvec_to_float4},
	{"halfvec_typmod_in", halfvec_typmod_in},
	{"halfvec_vector_dims", halfvec_vector_dims},
	{"sparsevec_to_halfvec", sparsevec_to_halfvec},
	{"vector_to_halfvec", vector_to_halfvec},
	{"hnswhandler", hnswhandler},
	{"hnsw_bit_support", hnsw_bit_support},
	{"hnsw_halfvec_support", hnsw_halfvec_support},
	{"hnsw_sparsevec_support", hnsw_sparsevec_support},
	{"ivfflathandler", ivfflathandler},
	{"ivfflat_bit_support", ivfflat_bit_support},
	{"ivfflat_halfvec_support", ivfflat_halfvec_support},
	{"array_to_sparsevec", array_to_sparsevec},
	{"halfvec_to_sparsevec", halfvec_to_sparsevec},
	{"sparsevec", sparsevec},
	{"sparsevec_cmp", sparsevec_cmp},
	{"sparsevec_cosine_distance", sparsevec_cosine_distance},
	{"sparsevec_eq", sparsevec_eq},
	{"sparsevec_ge", sparsevec_ge},
	{"sparsevec_gt", sparsevec_gt},
	{"sparsevec_in", sparsevec_in},
	{"sparsevec_inner_product", sparsevec_inner_product},
	{"sparsevec_l1_distance", sparsevec_l1_distance},
	{"sparsevec_l2_distance", sparsevec_l2_distance},
	{"sparsevec_l2_norm", sparsevec_l2_norm},
	{"sparsevec_l2_normalize", sparsevec_l2_normalize},
	{"sparsevec_l2_squared_distance", sparsevec_l2_squared_distance},
	{"sparsevec_le", sparsevec_le},
	{"sparsevec_lt", sparsevec_lt},
	{"sparsevec_ne", sparsevec_ne},
	{"sparsevec_negative_inner_product", sparsevec_negative_inner_product},
	{"sparsevec_out", sparsevec_out},
	{"sparsevec_recv", sparsevec_recv},
	{"sparsevec_send", sparsevec_send},
	{"sparsevec_typmod_in", sparsevec_typmod_in},
	{"vector_to_sparsevec", vector_to_sparsevec},
	{"array_to_vector", array_to_vector},
	{"binary_quantize", binary_quantize},
	{"cosine_distance", cosine_distance},
	{"halfvec_to_vector", halfvec_to_vector},
	{"inner_product", inner_product},
	{"l1_distance", l1_distance},
	{"l2_distance", l2_distance},
	{"l2_normalize", l2_normalize},
	{"sparsevec_to_vector", sparsevec_to_vector},
	{"subvector", subvector},
	{"vector", vector},
	{"vector_accum", vector_accum},
	{"vector_add", vector_add},
	{"vector_avg", vector_avg},
	{"vector_cmp", vector_cmp},
	{"vector_combine", vector_combine},
	{"vector_concat", vector_concat},
	{"vector_dims", vector_dims},
	{"vector_eq", vector_eq},
	{"vector_ge", vector_ge},
	{"vector_gt", vector_gt},
	{"vector_in", vector_in},
	{"vector_l2_squared_distance", vector_l2_squared_distance},
	{"vector_le", vector_le},
	{"vector_lt", vector_lt},
	{"vector_mul", vector_mul},
	{"vector_ne", vector_ne},
	{"vector_negative_inner_product", vector_negative_inner_product},
	{"vector_norm", vector_norm},
	{"vector_out", vector_out},
	{"vector_recv", vector_recv},
	{"vector_send", vector_send},
	{"vector_spherical_distance", vector_spherical_distance},
	{"vector_sub", vector_sub},
	{"vector_to_float4", vector_to_float4},
	{"vector_typmod_in", vector_typmod_in},
	{NULL, NULL}
};

const StaticExtensionFInfo pgvector_static_finfo[] = {
	{"pg_finfo_hamming_distance", pg_finfo_hamming_distance},
	{"pg_finfo_jaccard_distance", pg_finfo_jaccard_distance},
	{"pg_finfo_array_to_halfvec", pg_finfo_array_to_halfvec},
	{"pg_finfo_halfvec", pg_finfo_halfvec},
	{"pg_finfo_halfvec_accum", pg_finfo_halfvec_accum},
	{"pg_finfo_halfvec_add", pg_finfo_halfvec_add},
	{"pg_finfo_halfvec_avg", pg_finfo_halfvec_avg},
	{"pg_finfo_halfvec_binary_quantize", pg_finfo_halfvec_binary_quantize},
	{"pg_finfo_halfvec_cmp", pg_finfo_halfvec_cmp},
	{"pg_finfo_halfvec_concat", pg_finfo_halfvec_concat},
	{"pg_finfo_halfvec_cosine_distance", pg_finfo_halfvec_cosine_distance},
	{"pg_finfo_halfvec_eq", pg_finfo_halfvec_eq},
	{"pg_finfo_halfvec_ge", pg_finfo_halfvec_ge},
	{"pg_finfo_halfvec_gt", pg_finfo_halfvec_gt},
	{"pg_finfo_halfvec_in", pg_finfo_halfvec_in},
	{"pg_finfo_halfvec_inner_product", pg_finfo_halfvec_inner_product},
	{"pg_finfo_halfvec_l1_distance", pg_finfo_halfvec_l1_distance},
	{"pg_finfo_halfvec_l2_distance", pg_finfo_halfvec_l2_distance},
	{"pg_finfo_halfvec_l2_norm", pg_finfo_halfvec_l2_norm},
	{"pg_finfo_halfvec_l2_normalize", pg_finfo_halfvec_l2_normalize},
	{"pg_finfo_halfvec_l2_squared_distance", pg_finfo_halfvec_l2_squared_distance},
	{"pg_finfo_halfvec_le", pg_finfo_halfvec_le},
	{"pg_finfo_halfvec_lt", pg_finfo_halfvec_lt},
	{"pg_finfo_halfvec_mul", pg_finfo_halfvec_mul},
	{"pg_finfo_halfvec_ne", pg_finfo_halfvec_ne},
	{"pg_finfo_halfvec_negative_inner_product", pg_finfo_halfvec_negative_inner_product},
	{"pg_finfo_halfvec_out", pg_finfo_halfvec_out},
	{"pg_finfo_halfvec_recv", pg_finfo_halfvec_recv},
	{"pg_finfo_halfvec_send", pg_finfo_halfvec_send},
	{"pg_finfo_halfvec_spherical_distance", pg_finfo_halfvec_spherical_distance},
	{"pg_finfo_halfvec_sub", pg_finfo_halfvec_sub},
	{"pg_finfo_halfvec_subvector", pg_finfo_halfvec_subvector},
	{"pg_finfo_halfvec_to_float4", pg_finfo_halfvec_to_float4},
	{"pg_finfo_halfvec_typmod_in", pg_finfo_halfvec_typmod_in},
	{"pg_finfo_halfvec_vector_dims", pg_finfo_halfvec_vector_dims},
	{"pg_finfo_sparsevec_to_halfvec", pg_finfo_sparsevec_to_halfvec},
	{"pg_finfo_vector_to_halfvec", pg_finfo_vector_to_halfvec},
	{"pg_finfo_hnswhandler", pg_finfo_hnswhandler},
	{"pg_finfo_hnsw_bit_support", pg_finfo_hnsw_bit_support},
	{"pg_finfo_hnsw_halfvec_support", pg_finfo_hnsw_halfvec_support},
	{"pg_finfo_hnsw_sparsevec_support", pg_finfo_hnsw_sparsevec_support},
	{"pg_finfo_ivfflathandler", pg_finfo_ivfflathandler},
	{"pg_finfo_ivfflat_bit_support", pg_finfo_ivfflat_bit_support},
	{"pg_finfo_ivfflat_halfvec_support", pg_finfo_ivfflat_halfvec_support},
	{"pg_finfo_array_to_sparsevec", pg_finfo_array_to_sparsevec},
	{"pg_finfo_halfvec_to_sparsevec", pg_finfo_halfvec_to_sparsevec},
	{"pg_finfo_sparsevec", pg_finfo_sparsevec},
	{"pg_finfo_sparsevec_cmp", pg_finfo_sparsevec_cmp},
	{"pg_finfo_sparsevec_cosine_distance", pg_finfo_sparsevec_cosine_distance},
	{"pg_finfo_sparsevec_eq", pg_finfo_sparsevec_eq},
	{"pg_finfo_sparsevec_ge", pg_finfo_sparsevec_ge},
	{"pg_finfo_sparsevec_gt", pg_finfo_sparsevec_gt},
	{"pg_finfo_sparsevec_in", pg_finfo_sparsevec_in},
	{"pg_finfo_sparsevec_inner_product", pg_finfo_sparsevec_inner_product},
	{"pg_finfo_sparsevec_l1_distance", pg_finfo_sparsevec_l1_distance},
	{"pg_finfo_sparsevec_l2_distance", pg_finfo_sparsevec_l2_distance},
	{"pg_finfo_sparsevec_l2_norm", pg_finfo_sparsevec_l2_norm},
	{"pg_finfo_sparsevec_l2_normalize", pg_finfo_sparsevec_l2_normalize},
	{"pg_finfo_sparsevec_l2_squared_distance", pg_finfo_sparsevec_l2_squared_distance},
	{"pg_finfo_sparsevec_le", pg_finfo_sparsevec_le},
	{"pg_finfo_sparsevec_lt", pg_finfo_sparsevec_lt},
	{"pg_finfo_sparsevec_ne", pg_finfo_sparsevec_ne},
	{"pg_finfo_sparsevec_negative_inner_product", pg_finfo_sparsevec_negative_inner_product},
	{"pg_finfo_sparsevec_out", pg_finfo_sparsevec_out},
	{"pg_finfo_sparsevec_recv", pg_finfo_sparsevec_recv},
	{"pg_finfo_sparsevec_send", pg_finfo_sparsevec_send},
	{"pg_finfo_sparsevec_typmod_in", pg_finfo_sparsevec_typmod_in},
	{"pg_finfo_vector_to_sparsevec", pg_finfo_vector_to_sparsevec},
	{"pg_finfo_array_to_vector", pg_finfo_array_to_vector},
	{"pg_finfo_binary_quantize", pg_finfo_binary_quantize},
	{"pg_finfo_cosine_distance", pg_finfo_cosine_distance},
	{"pg_finfo_halfvec_to_vector", pg_finfo_halfvec_to_vector},
	{"pg_finfo_inner_product", pg_finfo_inner_product},
	{"pg_finfo_l1_distance", pg_finfo_l1_distance},
	{"pg_finfo_l2_distance", pg_finfo_l2_distance},
	{"pg_finfo_l2_normalize", pg_finfo_l2_normalize},
	{"pg_finfo_sparsevec_to_vector", pg_finfo_sparsevec_to_vector},
	{"pg_finfo_subvector", pg_finfo_subvector},
	{"pg_finfo_vector", pg_finfo_vector},
	{"pg_finfo_vector_accum", pg_finfo_vector_accum},
	{"pg_finfo_vector_add", pg_finfo_vector_add},
	{"pg_finfo_vector_avg", pg_finfo_vector_avg},
	{"pg_finfo_vector_cmp", pg_finfo_vector_cmp},
	{"pg_finfo_vector_combine", pg_finfo_vector_combine},
	{"pg_finfo_vector_concat", pg_finfo_vector_concat},
	{"pg_finfo_vector_dims", pg_finfo_vector_dims},
	{"pg_finfo_vector_eq", pg_finfo_vector_eq},
	{"pg_finfo_vector_ge", pg_finfo_vector_ge},
	{"pg_finfo_vector_gt", pg_finfo_vector_gt},
	{"pg_finfo_vector_in", pg_finfo_vector_in},
	{"pg_finfo_vector_l2_squared_distance", pg_finfo_vector_l2_squared_distance},
	{"pg_finfo_vector_le", pg_finfo_vector_le},
	{"pg_finfo_vector_lt", pg_finfo_vector_lt},
	{"pg_finfo_vector_mul", pg_finfo_vector_mul},
	{"pg_finfo_vector_ne", pg_finfo_vector_ne},
	{"pg_finfo_vector_negative_inner_product", pg_finfo_vector_negative_inner_product},
	{"pg_finfo_vector_norm", pg_finfo_vector_norm},
	{"pg_finfo_vector_out", pg_finfo_vector_out},
	{"pg_finfo_vector_recv", pg_finfo_vector_recv},
	{"pg_finfo_vector_send", pg_finfo_vector_send},
	{"pg_finfo_vector_spherical_distance", pg_finfo_vector_spherical_distance},
	{"pg_finfo_vector_sub", pg_finfo_vector_sub},
	{"pg_finfo_vector_to_float4", pg_finfo_vector_to_float4},
	{"pg_finfo_vector_typmod_in", pg_finfo_vector_typmod_in},
	{NULL, NULL}
};

void
register_pgvector(void)
{
	register_static_extension(
		"pgvector",
		pgvector_PG_init,
		pgvector_static_functions,
		pgvector_static_finfo
	);
}
